name: Package Zebar

concurrency: ci-build

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
  schedule:
    - cron:  '00 9 * * *'
  workflow_dispatch:

jobs:
  update_version:
    name: Update version
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Get latest version
      run: |
        VER=$(curl https://api.github.com/repos/glzr-io/zebar/releases/latest | jq '.["tag_name"]' | tr -d \")
        echo "version=$VER" >> $GITHUB_ENV
        echo "semver=${VER:1}" >> $GITHUB_ENV

    - name: Get file hash
      run: |
        wget --no-verbose https://github.com/glzr-io/zebar/releases/download/${{ env.version }}/zebar-${{ env.version }}-opt1-x64.msi
        HASH=$(sha256sum zebar-${{ env.version }}-opt1-x64.msi | awk "{print \$1}")
        echo "hash=$HASH" >> $GITHUB_ENV

    - name: Make install script
      run: |
        cat <<EOF > tools/chocolateyinstall.ps1
        \$ErrorActionPreference = 'Stop';
        \$params = @{
          packageName      = 'zebar'
          FileType         = 'msi'
          SilentArgs       = "/qn /norestart"
          validExitCodes   = @(0, 3010, 1641)
          Url64bit         = 'https://github.com/glzr-io/zebar/releases/download/${{ env.version }}/zebar-${{ env.version }}-opt1-x64.msi' 
          checksum64       = '${{ env.hash }}' 
          checksumType64   = 'sha256'
        }
        Install-ChocolateyPackage @params
        EOF

    - name: Make nuspec
      run: |
        cat << EOF > zebar.nuspec
        <?xml version="1.0" encoding="utf-8"?>
        <package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
          <metadata>
            <id>zebar</id>
            <version>${{ env.semver }}</version>
            <packageSourceUrl>https://github.com/rudesome/chocolateypackage-zebar</packageSourceUrl>
            <owners>rudesome</owners>
            <title>Zebar</title>
            <authors>glzr.io</authors>
            <projectUrl>https://github.com/glzr-io/zebar</projectUrl>
            <iconUrl>https://github.com/user-attachments/assets/d1e10485-2cbb-4434-9d98-5c74702eebcc</iconUrl>
            <licenseUrl>https://raw.githubusercontent.com/glzr-io/zebar/main/LICENSE.md</licenseUrl>
            <requireLicenseAcceptance>true</requireLicenseAcceptance>
            <projectSourceUrl>https://github.com/glzr-io/zebar</projectSourceUrl>
            <bugTrackerUrl>https://github.com/glzr-io/zebar/issues</bugTrackerUrl>
            <tags>statusbar desktop dock taskbar bar</tags>
            <summary>Zebar is a tool for creating customizable and cross-platform taskbars, desktop widgets, and popups. /summary>
            <description>
              Zebar lets you create customizable and cross-platform desktop widgets.
            </description>
            <releaseNotes>

            Release notes found here: https://github.com/glzr-io/zebar/releases/tag/${{ env.version }}

            </releaseNotes>
          </metadata>
          <files>
            <file src="tools\**" target="tools" />
          </files>
        </package>
        EOF

    - name: Remove EXE
      run: rm zebar*.msi

    - name: Write latest version to file
      run: echo -n ${{ env.version }} > VERSION

    - name: Commit and push changes
      id: push
      uses: devops-infra/action-commit-push@v0.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Updated to version ${{ env.version }}

  build:
    name: Chocolatey Build
    runs-on: windows-latest
    timeout-minutes: 15
    needs: update_version
    steps:
    - name: Checkout repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 

    - name: Choco Package 
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: pack 

    - name: Rename file
      run: mv zebar*.nupkg zebar.nupkg

    - name: Choco add API key
      if: ${{ env.updated }}
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: apikey -y -k ${{ secrets.CHOCO_TOKEN }} --source https://push.chocolatey.org/

    - name: Push to Chocolatey
      if: ${{ env.updated }}
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: push zebar.nupkg -s https://push.chocolatey.org/
